name: lint and format

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --group dev
          python -m pip install .
      - name: Run Ruff
        run: |
          python -m ruff check --output-format=github
          python -m ruff format --diff
      - name: Run Interrogate (docstrings)
        run: |
          python -m interrogate src/ tests/
      - name: Run mypy
        run: |
          python -m mypy src/
